### ISSUE TITLE
Make `drop_last` configurable in data loaders

### ISSUE THREAD

**Issue by aksarkar** [scverse/scvi-tools#2448]
**Is your feature request related to a problem? Please describe.**

A common gotcha with SCVI, etc. is encountering the following error in `BatchNorm1D`

```
Expected more than 1 value per channel when training, input size torch.Size([1, 128])
```

when the dimension of the data is such that the last minibatch has size 1. See for example #221, #426, #2214, #2314.

The previously accepted solutions have been to change the `batch_size` parameter to some value such that there is no batch of size 1.

However, this is not so easily accomplished for models like `scvi.external.SOLO`, where the actual training data size is not easily computed from the original data size unless one knows the technical details or follows the code very closely.

**Describe the solution you'd like**

The simplest solution to the problem would be to configure the training/validation data loaders with `drop_last=True`, since it is only the last batch that could have size 1.

Right now, this argument is hard-coded

https://github.com/scverse/scvi-tools/blob/9b5f5537ff5f8f1066e6a6170c4d5e6660b56793/scvi/dataloaders/_data_splitting.py#L488

Changing the default would eliminate a commonly occurring and confusing error. 

As an alternative, making it configurable via a keyword argument would provide a simpler solution to users who encounter the problem.

**Comment by martinkim0** [comment]
Hi, thanks for the suggestion. Unfortunately, we aren't planning on changing the default value of `drop_last` because of backwards compatibility. However, we do currently allow users to pass in this argument via `datasplitter_kwargs` (see [here](https://github.com/scverse/scvi-tools/blob/main/scvi/external/solo/_model.py#L302)), which will be passed in to the `AnnDataLoader` constructor. Let me know if this works for you.

**Comment by martinkim0** [comment]
Closing as the issue is addressed

**Comment by iyhaoo** [comment]
Hi, this issue doesn't solve yet, since in the latest version, it still make drop_last as false, then I cannot assign it as true...
https://github.com/scverse/scvi-tools/blob/95f2e1d2fa921c6433a04e257d844280ba0c25e5/scvi/dataloaders/_data_splitting.py#L145

**Comment by schroeme** [comment]
Hi @martinkim0, where can we pass drop_last=True in the SCVI model? It doesn't work if I pass it to `model.train()` or when setting up or initiating the model. I am having the same issue @aksarkar mentioned above with an `scvi.external.SOLO` model, where I can't tell what the minibatch size is (the number of cells in the batch % 128 is not 1). Thanks!

**Comment by schroeme** [comment]
After reading a bit more, I tried passing `drop_last=True` into `scvi.external.SOLO.train` via `datasplitter_kwargs` like so:

```
datasplitter_dict = {
  "drop_last": True
}
scvi.external.SOLO.train(solobatch, early_stopping = False,datasplitter_kwargs=datasplitter_dict)
```
and I get the following error:
`TypeError: scvi.dataloaders._data_splitting.DataSplitter() got multiple values for keyword argument 'batch_size'`.

I think this means `drop_last=False` is still hard-coded, no?

**Comment by seyoon-lee** [comment]
I am stuck exactly where @schroeme is right now as well. Just trying to pass datasplitter_kwargs={"drop_last":True}.

**Comment by rlinder02** [comment]
Hi @martinkim0, I'm having this issue too (I can't seem to find a place to add `drop_last=True`). The link you posted for `datasplitter kwargs` seems to be broken. Thanks!

**Comment by canergen** [comment]
Hi, I will push a fix later today. Sorry for the issues reported here. Please reopen issues when posting in closed issues. It is otherwise difficult to track these.

**Comment by rlinder02** [comment]
Thanks so much!
